apiVersion: apps/v1
kind: Deployment
metadata:
  name: fifo-backend
spec:
  selector:
    matchLabels:
      app: fifo-backend
  replicas: 2  
  template:
    metadata:
      labels:
        app: fifo-backend
    spec:
      containers:
      - name: fifo-backend
        image: mrpatel1234/fifo:fifo-backend
        imagePullPolicy: Always
        resources:
          limits: 
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: fifo-backend-service
spec:
  type: NodePort
  selector:
    app: fifo-backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001         
          
