apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  user: cm9vdA==
  password: cm9vdA==
---
# config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  ## name of ConfigMap. This will be referred from volume definition
  name: mysql-config
  labels:
    app: mysql-fifo
data:
  ## default_auth is the name of config. This will be referred from volume mount definition
  default_auth: |
    [mysqld]
    default_authentication_plugin= mysql_native_password
---    
apiVersion: v1
kind: Service
metadata:
  name: mysql-fifo-service
spec:
  selector:
    app: mysql-fifo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3306  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-fifo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-fifo
  labels:
    app: mysql-fifo
spec:
  selector:
    matchLabels:
      app: mysql-fifo
      tier: mysql-fifo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-fifo
        tier: mysql-fifo
    spec:
      containers:
      - image: mysql:5.7
        name: mysql-fifo
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: "fifo"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "root"   
        envFrom:
              - configMapRef:
                  name: mysql-config      
        ports:
        - containerPort: 3306
          name: mysql-fifo
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
