apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  user: cm9vdA==
  password: cm9vdA==
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-fifo
  labels:
    app: mysql-fifo
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-fifo
    tier: mysql-fifo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-fifo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-fifo
  labels:
    app: mysql-fifo
spec:
  selector:
    matchLabels:
      app: mysql-fifo
      tier: mysql-fifo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-fifo
        tier: mysql-fifo
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-fifo
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql-fifo
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
