apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-fifo-v1
spec:
  template:
    spec:
      containers:
      - name: flyway-fifo
        image: mrpatel1234/fifo:flyway
      restartPolicy: Never
