apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  user: cm9vdA==
  password: cm9vdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-service
  labels:
    app: mysqldb-service
spec:
  selector:
    matchLabels:
      app: mysqldb-service
  replicas: 1 
  template:
    metadata:
      labels:
        app: mysqldb-service
        tier: mysqldb-service
    spec:
      hostname: mysqldb-service
      containers:
      - name: mysqldb-service
        image: jamielsharief/mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          value: fifo            
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysqldb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
  labels:
    app: mysqldb-service
spec:
  type: NodePort
  selector:
    app: mysqldb-service
    tier: mysqldb-service
  ports:
  - port: 3001
    targetPort : 3001
    protocol: TCP